linter:
  rules:
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
