name: sunrise
description: A new Flutter project.
publish_to: "none"
version: 1.0.3
environment:
  sdk: "3.0.5"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  firebase_auth: ^4.2.6
  google_sign_in: ^6.1.4
  expandable: ^5.0.1
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^15.1.0
  http: ^1.1.0
  google_fonts: ^4.0.3
  firebase_crashlytics: ^3.0.15
  flutter_stripe: ^9.0.0
  equatable: ^2.0.5
  flutter_credit_card: ^3.0.6
  intl: ^0.18.1
  get_it: ^7.3.0
  result_dart: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/moods/
    - assets/
