name: sunrise
description: A new Flutter project.
publish_to: "none"
version: 1.1.001
environment:
  sdk: "3.1.5"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  firebase_auth: ^4.2.6
  google_sign_in: ^6.1.4
  expandable: ^5.0.1
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^16.1.0
  http: ^1.1.0
  google_fonts: ^6.1.0
  firebase_crashlytics: ^3.0.15
  flutter_stripe: ^9.3.0
  equatable: ^2.0.5
  intl: ^0.18.0
  get_it: ^7.3.0
  result_dart: ^1.1.0
  flutter_timezone: ^1.0.7
  flutter_localization: ^0.1.13
  purchases_flutter: ^6.1.0
_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/moods/
    - assets/config/
    - assets/
