// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByo5-uznasJMj3bcd63xxT62bbv9wHg_M',
    appId: '1:337324865218:web:69781e3b969a0761cded5b',
    messagingSenderId: '337324865218',
    projectId: 'sunrise-a2153',
    authDomain: 'sunrise-a2153.firebaseapp.com',
    storageBucket: 'sunrise-a2153.appspot.com',
    measurementId: 'G-QTQLZYQHJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxtFodBblwdm_DZTULjj04JJ3K-U7_aYQ',
    appId: '1:337324865218:android:a8c69c10a51b07facded5b',
    messagingSenderId: '337324865218',
    projectId: 'sunrise-a2153',
    storageBucket: 'sunrise-a2153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC698JgY95fw5CyCCsqhSVeC_ptLq5T-Y8',
    appId: '1:337324865218:ios:b5da56bcf9e9ccdacded5b',
    messagingSenderId: '337324865218',
    projectId: 'sunrise-a2153',
    storageBucket: 'sunrise-a2153.appspot.com',
    iosClientId: '337324865218-vpm6oua6nn6nbslp2g52l2n0srn7i2gk.apps.googleusercontent.com',
    iosBundleId: 'com.inora.sunrise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC698JgY95fw5CyCCsqhSVeC_ptLq5T-Y8',
    appId: '1:337324865218:ios:b5da56bcf9e9ccdacded5b',
    messagingSenderId: '337324865218',
    projectId: 'sunrise-a2153',
    storageBucket: 'sunrise-a2153.appspot.com',
    iosClientId: '337324865218-vpm6oua6nn6nbslp2g52l2n0srn7i2gk.apps.googleusercontent.com',
    iosBundleId: 'com.inora.sunrise',
  );
}
